---
extends: eslint:recommended
parserOptions:
  ecmaVersion: 8
env:
  es6: true
  node: true
rules:
  semi:
    - error
    - always
  prefer-const:
    - error
  quotes:
    - error
    - double
    - avoidEscape: true
  comma-dangle:
    - error
    - always-multiline
  no-unused-vars:
    - error
    - argsIgnorePattern: "^_"
